extract_tag_der_recursive: fix compilation errors
Fix the following errors introduced by extract_tag_der_recursive usage:

decoding.c: In function 'extract_tag_der_recursive':
decoding.c:560:5: error: 'ris' may be used uninitialized in this function [-Werror=maybe-uninitialized]

decoding.c: In function 'asn1_der_decoding_startEnd':
decoding.c:2192:40: error: unused variable 'p3' [-Werror=unused-variable]

Signed-off-by: Nikos Mavrogiannopoulos <nmav@redhat.com>